apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: popeye
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gabrieloliveers/desafio-gitops.git'
    targetRevision: main
    path: 'desafio-gitops/manifests/popeye'
  destination:
    namespace: popeye
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true